<a href="https://colab.research.google.com/github/Dhruvpalsinh/Word-Embeddings/blob/main/TEXT_REPRESENTATION_WORD_EMBEDDINGS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Some Common Terms to remember:

1. Corpus
2. Vocabulary
3. Document
4. Word

In [ ]:
# @title Bag of Word `DATASET CREATION`

import numpy as np
import pandas as pd

df = pd.DataFrame({
    'text': [
        'people watch campusx',
        'campusx watch campusx',
        'people write comment',
        'campusx write comment'
    ],
    'output': [1,1,0,0]
})

df

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
# @title USING `sklearn` `counVercorizer` perform `BAG OF WORDS`
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [ ]:
# @title BOW IMPLEMENTATTION
bow = cv.fit_transform(df['text'])

In [ ]:
# VOCABULARY
# It will assign index numver to all the unique words
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [ ]:
# BOW ARRAY
bow.toarray()

#Check in order, 1.campusx  2.Comment 3. people 4. watch 5. write in sentence wise

array([[1, 0, 1, 1, 0],
       [2, 0, 0, 1, 0],
       [0, 1, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]

In [ ]:
# @title Add New Sentence & Perform `BOW`
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]])

In [ ]:
# @title Store Output of `BOW`

X = bow.toarray()
y = df['output']

# N-grams

In [ ]:
# @title Default title text

In [ ]:
# @title N-Grams

import numpy as np
import pandas as pd

df = pd.DataFrame({
    'text': [
        'people watch campusx',
        'campusx watch campusx',
        'people write comment',
        'campusx write comment'
    ],
    'output': [1,1,0,0]
})

df

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
# @title USING `N-GRAMS`
# BI grams

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(2,2))
# TI grams
# cv = CountVectorizer(ngram_range=(3,3))
# BI & TI grams
# cv = CountVectorizer(ngram_range=(1,3))

In [ ]:
bow_ngram = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}

In [ ]:
print(bow_ngram[0].toarray())
#First sentence
#people watch campusx
#people watch
#watch campusx
#people watch  -> column 2
#watch campusx -> column 4
#column:        0 1 2 3 4 5
#               ↓ ↓ ↓ ↓ ↓ ↓
#vector:        0 0 1 0 1 0
#Means:
#campusx watch  = 0
#campusx write  = 0
#eople watch   = 1   ← present
#people write   = 0
#watch campusx  = 1   ← present
#write comment  = 0
print(bow_ngram[1].toarray())
print(bow_ngram[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]

# TF-IDF (Term frequency - Inverse Dcoument Frequency)

In [ ]:
# @title Example using `TF-IDF`
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
arr = tfidf.fit_transform(df['text']).toarray()
arr

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [ ]:
print(tfidf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]

### **WORD2VEC**

In [ ]:
# @title important libraries for `WORD2VEC`

import numpy as np
import pandas as pd
!pip install --upgrade gensim --user

# Import sys and os to manipulate Python's search path
import sys
import os

# Explicitly add the user site-packages directory to sys.path.
# This ensures the Python interpreter can find modules installed with --user
user_site_packages = os.path.expanduser(f'~/.local/lib/python{sys.version_info.major}.{sys.version_info.minor}/site-packages')
if user_site_packages not in sys.path:
    sys.path.insert(0, user_site_packages)

import gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.3.0)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 35.8 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
# @title Data Preprocessing

from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
story = []
for filename in os.listdir('data'):
  if filename == '.ipynb_checkpoints':
    pass
  f = open(os.path.join('data', filename))
  corpus = f.read()
  #sent_tokenize() breaks a large paragraph into individual sentences.
  # This is called Sentence Tokenization.
  raw_sent = sent_tokenize(corpus)
  #print(raw_sent)
  for sent in raw_sent:
    #Clean and tokenize the sentence
    # Means : Converts text to lowercase
    #Removes punctuation
    #Splits the sentence into individual words
    story.append(simple_preprocess(sent))

FileNotFoundError: [Errno 2] No such file or directory: 'data'

In [ ]:
story

In [ ]:
story[0]

In [ ]:
# Initialize gensim model
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [ ]:
# Vector Representation
# Step 1 : Create an empty brain 🧠
# Step 2 : Build vocabulary
  # Read all words
  # Find unique words
  # Assign internal IDs/numbers
# Step 3: Learn relationships
  # i.e king ↔ queen
        # cat  ↔ dog
        # king ↔ powerful
        # cat  ↔ milk
# Final Conversion :
  #king  → [0.21, -0.55, 0.81, ...]
  #queen → [0.19, -0.51, 0.79, ...]
  #cat   → [-0.72, 0.14, 0.33, ...]
model.build_vocab(story)

In [ ]:
# Train Model
#An epoch means:
  #One complete round of learning through the entire dataset.
#Corpus : How many training examples/sentences are there?
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

In [ ]:
model.wv.most_similar('daenerys')

In [ ]:
model.wv.similarity('arya', 'sansa')

In [ ]:
model.wv['deep'].shape

In [ ]:
# Get all the vectors
vec = model.wv.get_normed_vectors()
vec

In [ ]:
#y[0] → "king"
#y[1] → "queen"
#y[2] → "man"
#y[3] → "woman"
y = model.wv.index_to_key
len(y)

y

In [ ]:

from sklearn.decomposition import PCA

pca = PCA(n_components=3)
#X[0] → [2.1, 1.5]   → king
#X[1] → [2.0, 1.7]   → queen
#X[2] → [1.4, 0.8]   → man
#X[3] → [1.3, 1.0]   → woman
X = pca.fit_transform(vec)
X
#Relationship
#y[0]  ←→  X[0]
#y[1]  ←→  X[1]
#y[2]  ←→  X[2]
#y[3]  ←→  X[3]

In [ ]:
X.shape

In [ ]:
# Plot graph 3D
import plotly.express as px
fig = px.scatter_3d(X[200:300], x=0, y=1, z=2, color=y[200:300])
fig.show()